[workspace]
resolver = "3"
members = [
    "crates/kutworld",
    "crates/kutworld-codegen",
    "crates/kutworld-macros",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kutayyildiz/kutflow"
authors = ["Kutay YILDIZ <mail@kutayyildiz.com>"]
readme = "README.md"
